# Generated by Django 6.0.4 on 2026-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobportalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
