# Generated by Django 6.0.4 on 2026-05-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobportalApp', '0002_jobpostmodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_profilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to=settings.AUTH_USER_MODEL),
        ),
    ]
