# Generated by Django 6.0.4 on 2026-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobportalApp', '0003_alter_s_profilemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpostmodel',
            name='skill_set',
        ),
        migrations.RemoveField(
            model_name='s_profilemodel',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobpostmodel',
            name='skill_set',
            field=models.ManyToManyField(blank=True, to='JobportalApp.skill'),
        ),
        migrations.AddField(
            model_name='s_profilemodel',
            name='skill',
            field=models.ManyToManyField(blank=True, to='JobportalApp.skill'),
        ),
    ]
